CREATE TABLE IF NOT EXISTS setor (
  id INTEGER IDENTITY PRIMARY KEY,

  descricao VARCHAR(80) NOT NULL
);

INSERT INTO setor (id, descricao) VALUES (1,'Tecnologia');
INSERT INTO setor (id, descricao) VALUES (2,'RH');

CREATE TABLE colaborador (
  id INTEGER IDENTITY PRIMARY KEY,

  nome VARCHAR(80) NOT NULL,
  cpf VARCHAR(80) NOT NULL,
  setor_id BIGINT  NOT NULL,
  idade  BIGINT  NULL,
  email VARCHAR(80)  NULL,
  telefone VARCHAR(80)  NULL,
  FOREIGN KEY (setor_id) REFERENCES setor(id)
);

INSERT INTO colaborador (id, nome, cpf, email, telefone, setor_id, idade)
VALUES (1,'Rodrigo', '942.655.830-67','email@gmail.com','11111111', 1, 30);

INSERT INTO colaborador (id,nome, cpf, email, telefone, setor_id, idade)
VALUES (2,'Gustavo', '114.813.910-97', 'email@gmail.com','11111111', 1, 17);

--CREATE SEQUENCE setor_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
 --INT PRIMARY KEY AUTO_INCREMENT,--int not null primary key ,--BIGINT GENERATED BY DEFAULT AS SEQUENCE setor_id_seq PRIMARY KEY,